import { AccountPasswordV1Docs } from 'src/app/controllers/accountPasswordV1/accountPassword.docs';
import { AddDeviceBiometricPasswordV1Docs } from 'src/app/controllers/addDeviceBiometricPasswordV1/addDeviceBiometricPassword.docs';
import { AppointmentDocumentPDFV1Docs } from 'src/app/controllers/appointmentDocumentPDFV1/appointmentDocumentPDF.docs';
import { AppointmentTypesListV1Docs } from 'src/app/controllers/appointmentTypesListV1/appointmentTypesList.docs';
import { AvailabilityListV1Docs } from 'src/app/controllers/availabilityListV1/availabilityList.docs';
import { CancelAppointmentV1Docs } from 'src/app/controllers/cancelAppointmentV1/cancelAppointment.docs';
import { ConfirmVerificationOTPV1Docs } from 'src/app/controllers/confirmVerificationOtpV1/confirmVerificationOtp.docs';
import { CreateAppointmentV1Docs } from 'src/app/controllers/createAppointmentV1/createAppointment.docs';
import { CreatePatientV1Docs } from 'src/app/controllers/createPatientV1/createPatient.docs';
import { CreateRelativeInformationV1Docs } from 'src/app/controllers/createRelativeInformationV1/createRelativeInformation.docs';
import { CreateRelativeV1Docs } from 'src/app/controllers/createRelativeV1/createRelative.docs';
import { DeleteBiometricPasswordV1Docs } from 'src/app/controllers/deleteBiometricPasswordV1/deleteBiometricPassword.docs';
import { DeletePatientAccountV1Docs } from 'src/app/controllers/deletePatientAccountV1/deletePatientAccount.docs';
import { DeleteRelativeV1Docs } from 'src/app/controllers/deleteRelativeV1/deleteRelative.docs';
import { DoctorsListV1Docs } from 'src/app/controllers/doctorsListV1/doctorsList.docs';
import { GenerateCardTokenV1Docs } from 'src/app/controllers/generateCardTokenV1/generateCardToken.docs';
import { GuaranteeLetterListV1Docs } from 'src/app/controllers/guaranteeLetterListV1/guaranteeLetterList.docs';
import { HealthInsuranceDataV1Docs } from 'src/app/controllers/healthInsuranceDataV1/healthInsuranceData.docs';
import { HealthInsuranceViewV1Docs } from 'src/app/controllers/healthInsuranceViewV1/healthInsuranceView.docs';
import { InformInsuranceInterestV1Docs } from 'src/app/controllers/informInsuranceInterestV1/informInsuranceInterest.docs';
import { InsurancesListV1Docs } from 'src/app/controllers/insurancesListV1/insurancesList.docs';
import { InsuredPatientDuesV1Docs } from 'src/app/controllers/insuredPatientDuesV1/insuredPatientDues.docs';
import { OperateX12V1Docs } from 'src/app/controllers/operateX12V1/operateX12.docs';
import { PatientAppointmentDetailV1Docs } from 'src/app/controllers/patientAppointmentDetailV1/patientAppointmentDetail.docs';
import { PatientAppointmentsV1Docs } from 'src/app/controllers/patientAppointmentsV1/patientAppointments.docs';
import { PatientProfileV1Docs } from 'src/app/controllers/patientProfileV1/patientProfile.docs';
import { PatientRelativesV1Docs } from 'src/app/controllers/patientRelativesV1/patientRelatives.docs';
import { PatientReportsListV1Docs } from 'src/app/controllers/patientReportsListV1/patientReportsList.docs';
import { PatientResultPDFV1Docs } from 'src/app/controllers/patientResultPDFV1/patientResultPDF.docs';
import { PatientResultsListV1Docs } from 'src/app/controllers/patientResultsListV1/patientResultsList.docs';
import { PatientResultURLV1Docs } from 'src/app/controllers/patientResultURLV1/patientResultURL.docs';
import { PatientsListV1Docs } from 'src/app/controllers/patientsListV1/patientAppointments.docs';
import { PatientVerificationV1Docs } from 'src/app/controllers/patientVerificationV1/patientVerification.docs';
import { PayAppointmentV1Docs } from 'src/app/controllers/payAppointmentV1/payHealthInsurance.docs';
import { PayHealthInsuranceV1Docs } from 'src/app/controllers/payHealthInsuranceV1/payHealthInsurance.docs';
import { POSConfigV1Docs } from 'src/app/controllers/posConfigV1/posConfig.docs';
import { RejectRelativeV1Docs } from 'src/app/controllers/rejectRelativeV1/rejectRelative.docs';
import { RelationshipsListV1Docs } from 'src/app/controllers/relationshipsListV1/relationshipsList.docs';
import { RelativeVerificationV1Docs } from 'src/app/controllers/relativeVerificationV1/relativeVerification.docs';
import { RescheduleAppointmentV1Docs } from 'src/app/controllers/rescheduleAppointmentV1/rescheduleAppointment.docs';
import { SendDeepLinkNotificationV1Docs } from 'src/app/controllers/sendDeepLinkNotificationV1/sendDeepLinkNotification.docs';
import { SendNotificationV1Docs } from 'src/app/controllers/sendNotificationV1/sendNotification.docs';
import { SendVerificationOTPV1Docs } from 'src/app/controllers/sendVerificationOtpV1/sendVerificationOtp.docs';
import { SignInEmployeeV1Docs } from 'src/app/controllers/signInEmployeeV1/signInEmployee.docs';
import { SignInPatientV1Docs } from 'src/app/controllers/signInPatientV1/signInPatient.docs';
import { SignOutPatientV1Docs } from 'src/app/controllers/signOutPatientV1/signOutPatient.docs';
import { SitedsPriceV1Docs } from 'src/app/controllers/sitedsPriceV1/sitedsPrice.docs';
import { SpecialtiesListV1Docs } from 'src/app/controllers/specialtiesListV1/specialtiesList.docs';
import { UpdateHealthInsuranceV1Docs } from 'src/app/controllers/updateHealthInsuranceV1/updateHealthInsurance.docs';
import { VerifyRelativeV1Docs } from 'src/app/controllers/verifyRelativeV1/verifyRelative.docs';
import type { OpenApiManager } from 'src/general/managers/openapi/openapi.manager';

export class DocsBuilder {
  static build(manager: OpenApiManager): void {
    new AccountPasswordV1Docs(manager).registerDocs();
    new AddDeviceBiometricPasswordV1Docs(manager).registerDocs();
    new AppointmentTypesListV1Docs(manager).registerDocs();
    new AvailabilityListV1Docs(manager).registerDocs();
    new ConfirmVerificationOTPV1Docs(manager).registerDocs();
    new CreateAppointmentV1Docs(manager).registerDocs();
    new DeleteBiometricPasswordV1Docs(manager).registerDocs();
    new DeletePatientAccountV1Docs(manager).registerDocs();
    new DoctorsListV1Docs(manager).registerDocs();
    new InsurancesListV1Docs(manager).registerDocs();
    new PatientAppointmentsV1Docs(manager).registerDocs();
    new PatientProfileV1Docs(manager).registerDocs();
    new PatientRelativesV1Docs(manager).registerDocs();
    new PatientVerificationV1Docs(manager).registerDocs();
    new SendVerificationOTPV1Docs(manager).registerDocs();
    new SignInPatientV1Docs(manager).registerDocs();
    new SignOutPatientV1Docs(manager).registerDocs();
    new SpecialtiesListV1Docs(manager).registerDocs();
    new PatientAppointmentDetailV1Docs(manager).registerDocs();
    new CancelAppointmentV1Docs(manager).registerDocs();
    new RescheduleAppointmentV1Docs(manager).registerDocs();
    new CreatePatientV1Docs(manager).registerDocs();
    new InsuredPatientDuesV1Docs(manager).registerDocs();
    new HealthInsuranceViewV1Docs(manager).registerDocs();
    new POSConfigV1Docs(manager).registerDocs();
    new RelationshipsListV1Docs(manager).registerDocs();
    new RelativeVerificationV1Docs(manager).registerDocs();
    new CreateRelativeInformationV1Docs(manager).registerDocs();
    new CreateRelativeV1Docs(manager).registerDocs();
    new DeleteRelativeV1Docs(manager).registerDocs();
    new InformInsuranceInterestV1Docs(manager).registerDocs();
    new SitedsPriceV1Docs(manager).registerDocs();
    new PayHealthInsuranceV1Docs(manager).registerDocs();
    new AppointmentDocumentPDFV1Docs(manager).registerDocs();
    new GuaranteeLetterListV1Docs(manager).registerDocs();
    new PatientReportsListV1Docs(manager).registerDocs();
    new PatientResultsListV1Docs(manager).registerDocs();
    new PatientResultPDFV1Docs(manager).registerDocs();
    new PatientResultURLV1Docs(manager).registerDocs();
    new PayAppointmentV1Docs(manager).registerDocs();
    new SignInEmployeeV1Docs(manager).registerDocs();
    new PatientsListV1Docs(manager).registerDocs();
    new HealthInsuranceDataV1Docs(manager).registerDocs();
    new UpdateHealthInsuranceV1Docs(manager).registerDocs();
    new VerifyRelativeV1Docs(manager).registerDocs();
    new RejectRelativeV1Docs(manager).registerDocs();
    new SendNotificationV1Docs(manager).registerDocs();
    new SendDeepLinkNotificationV1Docs(manager).registerDocs();
    new OperateX12V1Docs(manager).registerDocs();
    new GenerateCardTokenV1Docs(manager).registerDocs();
  }
}
