import type { FastifyInstance } from 'fastify';

import { AccountPasswordV1Router } from 'src/app/controllers/accountPasswordV1/accountPassword.router';
import { AddDeviceBiometricPasswordV1Router } from 'src/app/controllers/addDeviceBiometricPasswordV1/addDeviceBiometricPassword.router';
import { AppointmentDocumentPDFV1Router } from 'src/app/controllers/appointmentDocumentPDFV1/appointmentDocumentPDF.router';
import { AppointmentTypesListV1Router } from 'src/app/controllers/appointmentTypesListV1/appointmentTypesList.router';
import { AvailabilityListV1Router } from 'src/app/controllers/availabilityListV1/availabilityList.router';
import { CancelAppointmentV1Router } from 'src/app/controllers/cancelAppointmentV1/cancelAppointment.router';
import { ConfirmVerificationOTPV1Router } from 'src/app/controllers/confirmVerificationOtpV1/confirmVerificationOtp.routes';
import { CreateAppointmentV1Router } from 'src/app/controllers/createAppointmentV1/createAppointment.router';
import { CreatePatientV1Router } from 'src/app/controllers/createPatientV1/createPatient.router';
import { CreateRelativeInformationV1Router } from 'src/app/controllers/createRelativeInformationV1/createRelativeInformation.router';
import { CreateRelativeV1Router } from 'src/app/controllers/createRelativeV1/createRelative.router';
import { DeleteBiometricPasswordV1Router } from 'src/app/controllers/deleteBiometricPasswordV1/deleteBiometricPassword.router';
import { DeletePatientAccountV1Router } from 'src/app/controllers/deletePatientAccountV1/deletePatientAccount.router';
import { DeleteRelativeV1Router } from 'src/app/controllers/deleteRelativeV1/deleteRelative.router';
import { DoctorsListV1Router } from 'src/app/controllers/doctorsListV1/doctorsList.router';
import { GenerateCardTokenV1Router } from 'src/app/controllers/generateCardTokenV1/generateCardToken.router';
import { GuaranteeLetterListV1Router } from 'src/app/controllers/guaranteeLetterListV1/guaranteeLetterList.router';
import { HealthInsuranceDataV1Router } from 'src/app/controllers/healthInsuranceDataV1/healthInsuranceData.router';
import { HealthInsuranceViewV1Router } from 'src/app/controllers/healthInsuranceViewV1/healthInsuranceView.routes';
import { InformInsuranceInterestV1Router } from 'src/app/controllers/informInsuranceInterestV1/informInsuranceInterest.router';
import { InsurancesListV1Router } from 'src/app/controllers/insurancesListV1/insurancesList.router';
import { InsuredPatientDuesV1Router } from 'src/app/controllers/insuredPatientDuesV1/insuredPatientDues.router';
import { OperateX12V1Router } from 'src/app/controllers/operateX12V1/operateX12.router';
import { PatientAppointmentDetailV1Router } from 'src/app/controllers/patientAppointmentDetailV1/patientAppointmentDetail.router';
import { PatientAppointmentsV1Router } from 'src/app/controllers/patientAppointmentsV1/patientAppointments.router';
import { PatientProfileV1Router } from 'src/app/controllers/patientProfileV1/patientProfile.router';
import { PatientRelativesV1Router } from 'src/app/controllers/patientRelativesV1/patientRelatives.routes';
import { PatientReportsListV1Router } from 'src/app/controllers/patientReportsListV1/patientReportsList.router';
import { PatientResultPDFV1Router } from 'src/app/controllers/patientResultPDFV1/patientResultPDF.router';
import { PatientResultsListV1Router } from 'src/app/controllers/patientResultsListV1/patientResultsList.router';
import { PatientResultURLV1Router } from 'src/app/controllers/patientResultURLV1/patientResultURL.router';
import { PatientsListV1Router } from 'src/app/controllers/patientsListV1/patientsList.router';
import { PatientVerificationV1Router } from 'src/app/controllers/patientVerificationV1/patientVerification.routes';
import { PayAppointmentV1Router } from 'src/app/controllers/payAppointmentV1/payAppointment.router';
import { PayHealthInsuranceV1Router } from 'src/app/controllers/payHealthInsuranceV1/payHealthInsurance.router';
import { POSConfigV1Router } from 'src/app/controllers/posConfigV1/posConfig.router';
import { RejectRelativeV1Router } from 'src/app/controllers/rejectRelativeV1/rejectRelative.router';
import { RelationshipsListV1Router } from 'src/app/controllers/relationshipsListV1/relationshipsList.router';
import { RelativeVerificationV1Router } from 'src/app/controllers/relativeVerificationV1/relativeVerification.router';
import { RescheduleAppointmentV1Router } from 'src/app/controllers/rescheduleAppointmentV1/rescheduleAppointment.router';
import { SendDeepLinkNotificationV1Router } from 'src/app/controllers/sendDeepLinkNotificationV1/sendDeepLinkNotification.router';
import { SendNotificationV1Router } from 'src/app/controllers/sendNotificationV1/sendNotification.router';
import { SendVerificationOTPV1Router } from 'src/app/controllers/sendVerificationOtpV1/sendVerificationOtp.routes';
import { SignInEmployeeV1Router } from 'src/app/controllers/signInEmployeeV1/signInEmployee.routes';
import { SignInPatientV1Router } from 'src/app/controllers/signInPatientV1/signInPatient.routes';
import { SignOutPatientV1Router } from 'src/app/controllers/signOutPatientV1/signOutPatient.routes';
import { SitedsPriceV1Router } from 'src/app/controllers/sitedsPriceV1/sitedsPrice.router';
import { SpecialtiesListV1Router } from 'src/app/controllers/specialtiesListV1/specialtiesList.routes';
import { UpdateHealthInsuranceV1Router } from 'src/app/controllers/updateHealthInsuranceV1/updateHealthInsurance.router';
import { VerifyRelativeV1Router } from 'src/app/controllers/verifyRelativeV1/verifyRelative.router';

export class RouterBuilder {
  static build(fastify: FastifyInstance): void {
    new AccountPasswordV1Router(fastify).registerRouter();
    new AddDeviceBiometricPasswordV1Router(fastify).registerRouter();
    new AppointmentTypesListV1Router(fastify).registerRouter();
    new AvailabilityListV1Router(fastify).registerRouter();
    new ConfirmVerificationOTPV1Router(fastify).registerRouter();
    new CreateAppointmentV1Router(fastify).registerRouter();
    new DeleteBiometricPasswordV1Router(fastify).registerRouter();
    new DeletePatientAccountV1Router(fastify).registerRouter();
    new DoctorsListV1Router(fastify).registerRouter();
    new InsurancesListV1Router(fastify).registerRouter();
    new PatientAppointmentsV1Router(fastify).registerRouter();
    new PatientProfileV1Router(fastify).registerRouter();
    new PatientRelativesV1Router(fastify).registerRouter();
    new PatientVerificationV1Router(fastify).registerRouter();
    new SendVerificationOTPV1Router(fastify).registerRouter();
    new SignInPatientV1Router(fastify).registerRouter();
    new SignOutPatientV1Router(fastify).registerRouter();
    new SpecialtiesListV1Router(fastify).registerRouter();
    new PatientAppointmentDetailV1Router(fastify).registerRouter();
    new CancelAppointmentV1Router(fastify).registerRouter();
    new RescheduleAppointmentV1Router(fastify).registerRouter();
    new CreatePatientV1Router(fastify).registerRouter();
    new InsuredPatientDuesV1Router(fastify).registerRouter();
    new HealthInsuranceViewV1Router(fastify).registerRouter();
    new POSConfigV1Router(fastify).registerRouter();
    new RelationshipsListV1Router(fastify).registerRouter();
    new RelativeVerificationV1Router(fastify).registerRouter();
    new CreateRelativeInformationV1Router(fastify).registerRouter();
    new CreateRelativeV1Router(fastify).registerRouter();
    new DeleteRelativeV1Router(fastify).registerRouter();
    new InformInsuranceInterestV1Router(fastify).registerRouter();
    new SitedsPriceV1Router(fastify).registerRouter();
    new PayHealthInsuranceV1Router(fastify).registerRouter();
    new AppointmentDocumentPDFV1Router(fastify).registerRouter();
    new GuaranteeLetterListV1Router(fastify).registerRouter();
    new PatientReportsListV1Router(fastify).registerRouter();
    new PatientResultsListV1Router(fastify).registerRouter();
    new PatientResultPDFV1Router(fastify).registerRouter();
    new PatientResultURLV1Router(fastify).registerRouter();
    new PayAppointmentV1Router(fastify).registerRouter();
    new SignInEmployeeV1Router(fastify).registerRouter();
    new PatientsListV1Router(fastify).registerRouter();
    new HealthInsuranceDataV1Router(fastify).registerRouter();
    new UpdateHealthInsuranceV1Router(fastify).registerRouter();
    new VerifyRelativeV1Router(fastify).registerRouter();
    new RejectRelativeV1Router(fastify).registerRouter();
    new SendNotificationV1Router(fastify).registerRouter();
    new SendDeepLinkNotificationV1Router(fastify).registerRouter();
    new OperateX12V1Router(fastify).registerRouter();
    new GenerateCardTokenV1Router(fastify).registerRouter();
  }
}
