export const CRPConstants = {
  CENTER_ID: '051010100',
  ORIGIN: 'PERU',
  DEFAULT_COUNTRY: 'PER',
  DEFAULT_CURRENCY: 'S',
  DEFAULT_PATIENT_TYPE: '1',
  REQUEST_TIMEOUT: 120000,
  EXTERNAL_REQUEST_TIMEOUT: 60000,
  SITEDS_REQUEST_TIMEOUT: 15000,
  TOKEN_TIMEOUT: 55,
  UNDER_AGE_LIMIT: -18,
  EARLIEST_SLOT_LIMIT: 3,
} as const;
