export const CRPConstants = {
  CENTER_ID: '051010100',
  ORIGIN: 'PERU',
  DEFAULT_COUNTRY: 'PER',
  DEFAULT_CURRENCY: 'S',
  DEFAULT_PATIENT_TYPE: '1',
  SOAP_TIMEOUT: 30000,
  TOKEN_TIMEOUT: 55,
} as const;
