export const PosConstants = {
  DEFAULT_EMAIL: 'test@crp.com.pe',
  DEFAULT_MDD21: 0,
  DEFAULT_MDD75: 'Registrado',
  DEFAULT_CURRENCY: 'PEN',
  HASH_PREFIX: 'sha256/',
  DEFAULT_COUNTRY: 'PE',
  DEFAULT_CITY: 'LIM',
  DEFAULT_CITY_NAME: 'Lima',
  DEFAULT_ADDRESS: 'AV. JAVIER PRADO ESTE NRO. 1066 URB. CORPAC',
  DEFAULT_ZIP_CODE: '15036',
  DEFAULT_PHONE_NUMBER: '012242224',
  DEFAULT_IP: '0.0.0.0',
} as const;
