export const SitedsConstants = {
  IPRESS_ID: '00009409',
  RUC_NUMBER: '20100121809',
  DEFAULT_ENTITY_TYPE: '2',
  DEFAULT_PATIENT_TYPE: '1',
  DEFAULT_PURPOSE_CODE: '13',
  EXCEPTION_CODE: '0000',
  SUCCESS_CODE: '0000',
  DEFAULT_TRANSAC_NAME: '270_CON_ASE',
  DEFAULT_TRANSAC_ID: '270',
  DEFAULT_QUALIFIER: 'A4',
  DEFAULT_REQUEST: 'CN',
  ERROR_MESSAGES: {
    '0010': 'Estructura XML de entrada no corresponde a la definida',
    '0020': 'Error ocurrido en el flujo de proceso',
    '0030': 'LA VERSIÓN DEL SITEDS EN USO NO ES OFICIAL',
    '0100': 'Transacción no utilizada por la IAFAS',
    '0110': 'No ingreso código de Usuario',
    '0200': 'No ingreso Código de excepción',
    '0210': 'Código de excepción no existe',
    '0300': 'No ingreso nombre de Transacción Activa',
    '0310': 'No existe el nombre de la transacción',
    '0320': 'No ingreso fecha de inicio',
    '0330': 'Longitud de Fecha Inicio diferente de 8',
    '0340': 'Formato de Fecha Inicio incorrecta',
    '0350': 'No ingreso fecha de Fin',
    '0360': 'Longitud de Fecha Fin diferente de 8',
    '0370': 'Formato de Fecha Fin incorrecta',
    '0400': 'No ingreso código de IAFAS',
    '0401': 'El estado del asegurado NO es VIGENTE',
    '0410':
      'No existe código de IAFAS en BD SUSALUD/No coincide el códigos del remitente ingresado como parámetro y el enviado en la Trama',
    '0420': 'No ingreso código de IPRESS',
    '0430': 'No existe código de IPRESS',
    '0440': 'La IPRESS no tiene convenio con la IAFAS',
    '0500': 'No ingreso trama de Transacción',
    '0510': 'No ingreso Descripción de data',
    '0600': 'No se encontro información referente a la busqueda',
    '0700': 'Problemas al generar el objeto JSON',
    '0800': 'No ingreso el número de la versión',
    '0810': 'El número de la versión es un campo numérico',
    '0820': 'No existe actualizaciones posteriores a la versión ingresada',
    '0900': 'La estructura xml no es la correcta (WS-Security estandarizada por OASIS v1.1)',
    '0901': 'El usuario o contraseña del tokenusername es null(WS-Security)',
    '0902': 'La contraseña a descifrar no tiene la estructura correcta(WS-Security)',
    '0903': 'Usuario y contraseña no encontrados en Base de datos(WS-Security)',
    '0904': 'Problemas al invocar la clase que descifra la contraseña(WS-Security)',
    '1000': 'No ingreso ningún filtro de busqueda',
    '1002': 'No existe url del web services expuesto por la IAFAS en BD',
    '1004': 'Aplicativo Siteds encontro código de excepción',
    '1005': 'Error al intentar acceder al WS de expuesto por la IAFAS',
    '1006': 'Ingresar el DNI o los datos completos del apellido paterno, apellido materno y nombre(s)',
    '1007': 'No existe carta de garantía para el afiliado',
    '1008': 'El afiliado se excedió en el límite anual de cobertura del Plan',
    '1009': 'Tipo de atención no permitida. Tomar contacto con su aseguradora (IAFAS)',
    '1010': 'No se permite el registro de accidentes.',
    '1100': 'No existe el afiliado en la base de datos de SUSALUD',
    '1200': 'Se excedio el número de registros de respuesta',
    '1300': 'No existe el afiliado en la base de datos de la IAFAS',
    '1301': 'El asegurado está en estado INACTIVO',
    '1302': 'El asegurado está en estado SUSPENDIDO',
    '1303': 'El asegurado está en estado ANULADO',
    '1304': 'El asegurado está en estado SIN COBERTURA',
    '1400': 'No se encontraron actualizaciones en Base de Datos SUSALUD',
    '1500': 'Error en los datos del Afiliado de la transacción en curso',
    '1600': 'El número de acreditación ya se encuentra registrada en SUSALUD',
    '1601': 'No se ha generado el número de autorización por datos errado del asegurado en la petición',
    '9000': 'Error de base de datos',
    '9898': 'En estos momentos no hay comunicación con la IAFAS',
    '9999': 'Error de webservice',
  },
} as const;
