import { z } from 'zod';

export const ConAse270DTOSchema = z.object({
  transactionName: z.string().optional(),
  ipressId: z.string().optional(),
  iafaId: z.string().optional(),
  date: z.string().optional(),
  time: z.string().optional(),
  shortDate: z.string().optional(),
  shortTime: z.string().optional(),
  correlative: z.string().optional(),
  transactionId: z.string().optional(),
  purposeCode: z.string().optional(),
  senderEntityType: z.string().optional(),
  senderTaxId: z.string().optional(),
  requestText: z.string().optional(),
  receiverEntityType: z.string().optional(),
  patientEntityType: z.string().optional(),
  patientLastName: z.string().optional(),
  patientFirstName: z.string().optional(),
  patientMemberId: z.string().optional(),
  patientSecondLastName: z.string().optional(),
  documentType: z.string().optional(),
  documentNumber: z.string().optional(),
  productCode: z.string().optional(),
  productDescription: z.string().optional(),
  productInternalCode: z.string().optional(),
  coverageNumber: z.string().optional(),
  coverageDescription: z.string().optional(),
  serviceCategory: z.string().optional(),
  serviceClassCode: z.string().optional(),
  initialMaxBenefit: z.string().optional(),
  coverageTypeCode: z.string().optional(),
  coverageSubtypeCode: z.string().optional(),
  applicationCode: z.string().optional(),
  specialtyCode: z.string().optional(),
  relationshipCode: z.string().optional(),
  planNumber: z.string().optional(),
  originalAuthNumber: z.string().optional(),
  accidentType: z.string().optional(),
  accidentDate: z.string().optional(),
  contractorEntityType: z.string().optional(),
  contractorLastName: z.string().optional(),
  contractorFirstName: z.string().optional(),
  contractorSecondLastName: z.string().optional(),
  contractorDocumentType: z.string().optional(),
  contractorIdQualifier: z.string().optional(),
  contractorId: z.string().optional(),
  groupControlNumber: z.string().optional(),
  transactionSetControlNumber: z.string().optional(),
});

export type ConAse270DTO = z.infer<typeof ConAse270DTOSchema>;
