import { z } from 'zod';

import { ConCod271DetailDTOSchema } from './conCod271Detail.dto';

export const ConCod271DTOSchema = z.object({
  ipressId: z.string().optional(),
  iafaId: z.string().optional(),
  date: z.string().optional(),
  time: z.string().optional(),
  shortDate: z.string().optional(),
  shortTime: z.string().optional(),
  correlationId: z.string().optional(),
  transactionId: z.string().optional(),
  purposeCode: z.string().optional(),
  controlNumber: z.string().optional(),
  transactionSetControlNumber: z.string().optional(),
  senderCategory: z.string().optional(),
  senderUser: z.string().optional(),
  senderPassword: z.string().optional(),
  photoUploadDate: z.string().optional(),
  receiverCategory: z.string().optional(),
  receiverTaxId: z.string().optional(),
  patientCategory: z.string().optional(),
  patientLastName: z.string().optional(),
  patientFirstName: z.string().optional(),
  patientAffiliation: z.string().optional(),
  patientSecondLastName: z.string().optional(),
  patientStatusCode: z.string().optional(),
  patientDocumentType: z.string().optional(),
  patientDocumentNumber: z.string().optional(),
  patientIdentifier: z.string().optional(),
  patientContractNumber: z.string().optional(),
  policyNumber: z.string().optional(),
  certificateNumber: z.string().optional(),
  policyTypeCode: z.string().optional(),
  productCode: z.string().optional(),
  productDescription: z.string().optional(),
  planNumber: z.string().optional(),
  healthPlanType: z.string().optional(),
  currencyCode: z.string().optional(),
  relationshipCode: z.string().optional(),
  benefitSubjectCode: z.string().optional(),
  benefitSubjectNumber: z.string().optional(),
  birthDate: z.string().optional(),
  gender: z.string().optional(),
  maritalStatus: z.string().optional(),
  coverageStartDate: z.string().optional(),
  coverageEndDate: z.string().optional(),
  contractorCategory: z.string().optional(),
  contractorLastName: z.string().optional(),
  contractorFirstName: z.string().optional(),
  contractorSecondLastName: z.string().optional(),
  contractorDocumentType: z.string().optional(),
  contractorIdRef: z.string().optional(),
  contractorRefCode: z.string().optional(),
  holderCategory: z.string().optional(),
  holderLastName: z.string().optional(),
  holderFirstName: z.string().optional(),
  holderAffiliation: z.string().optional(),
  holderSecondLastName: z.string().optional(),
  holderDocumentType: z.string().optional(),
  holderDocumentNumber: z.string().optional(),
  holderEnrollmentDate: z.string().optional(),
  details: z.array(ConCod271DetailDTOSchema).optional(),
});

export type ConCod271DTO = z.infer<typeof ConCod271DTOSchema>;
