export const LogConstants = {
  MAX_VALUE_LENGTH: 2000,
  REDACTED_VALUE: '[Redacted]',
  CIRCULAR_VALUE: '[Circular]',
  SENSITIVE_KEYS: [
    'authorization',
    'apikey',
    'accesstoken',
    'refreshtoken',
    'sessiontoken',
    'tokenid',
    'pushtoken',
    'xpushtoken',
    'devicetoken',
    'transactiontoken',
    'token',
    'tokens',
    'password',
    'contrasena',
    'contrasenia',
    'senderpassword',
    'secret',
    'otp',
    'passwordhash',
    'passwordsalt',
    'otpsendcount',
    'pass',
    'pin',
    'pinhash',
    'card',
    'cardtoken',
    'cardnumber',
    'cvv',
    'email',
    'customeremail',
    'phone',
    'birthdate',
    'lastname',
    'secondlastname',
    'patientlastname',
    'patientsecondlastname',
    'clientlastname',
    'clientsecondlastname',
    'holderlastname',
    'holdersecondlastname',
    'contractorlastname',
    'contractorsecondlastname',
    'address',
    'siteds',
    'requesttext',
    'encodedpayload',
    'decodedpayload',
    'base64',
  ],
} as const;
