import { ConAse270DTO } from 'src/app/entities/dtos/service/conAse270.dto';

import { FieldMap, X12ManagerConfig } from '../x12.manager';

export class ConAse270Config implements X12ManagerConfig<ConAse270DTO> {
  readonly segmentDelimiter: string = '~';
  readonly elementDelimiter: string = '*';
  readonly componentDelimiter: string = ':';
  readonly segmentSequence: string[] = [
    'ISA',
    'GS',
    'ST',
    'BHT',
    'HL',
    'NM1',
    'PRV',
    'HL',
    'NM1',
    'HL',
    'NM1',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'DTP',
    'NM1',
    'REF',
    'SE',
    'GE',
    'IEA',
  ];
  readonly segmentLength: Record<string, number> = {
    ISA: 16,
    GS: 8,
    ST: 3,
    BHT: 2,
    HL: 4,
    NM1: 12,
    PRV: 3,
    REF: 3,
    DTP: 3,
    SE: 2,
    GE: 2,
    IEA: 2,
  };
  readonly fieldMap: FieldMap<ConAse270DTO> = {
    ipressId: [
      { tag: 'ISA', element: 6, occurrence: 1 },
      { tag: 'GS', element: 2, occurrence: 1 },
    ],
    iafaId: [
      { tag: 'ISA', element: 8, occurrence: 1 },
      { tag: 'GS', element: 3, occurrence: 1 },
      { tag: 'NM1', element: 9, occurrence: 2 },
    ],
    date: [{ tag: 'GS', element: 4, occurrence: 1 }],
    time: [{ tag: 'GS', element: 5, occurrence: 1 }],
    shortDate: [{ tag: 'ISA', element: 9, occurrence: 1 }],
    shortTime: [{ tag: 'ISA', element: 10, occurrence: 1 }],
    correlative: [
      { tag: 'ISA', element: 13, occurrence: 1 },
      { tag: 'IEA', element: 2, occurrence: 1 },
    ],
    transactionId: [{ tag: 'ST', element: 1, occurrence: 1 }],
    groupControlNumber: [
      { tag: 'GS', element: 6, occurrence: 1 },
      { tag: 'GE', element: 2, occurrence: 1 },
    ],
    transactionSetControlNumber: [
      { tag: 'ST', element: 2, occurrence: 1 },
      { tag: 'SE', element: 2, occurrence: 1 },
    ],
    purposeCode: [{ tag: 'BHT', element: 2, occurrence: 1 }],
    senderEntityType: [{ tag: 'NM1', element: 2, occurrence: 1 }],
    senderTaxId: [{ tag: 'NM1', element: 9, occurrence: 1 }],
    requestText: [{ tag: 'PRV', element: 3, occurrence: 1 }],
    receiverEntityType: [{ tag: 'NM1', element: 2, occurrence: 2 }],
    patientEntityType: [{ tag: 'NM1', element: 2, occurrence: 3 }],
    patientLastName: [{ tag: 'NM1', element: 3, occurrence: 3 }],
    patientFirstName: [{ tag: 'NM1', element: 4, occurrence: 3 }],
    patientMemberId: [{ tag: 'NM1', element: 9, occurrence: 3 }],
    patientSecondLastName: [{ tag: 'NM1', element: 12, occurrence: 3 }],
    documentType: [{ tag: 'REF', element: 2, occurrence: 1 }],
    documentNumber: [{ tag: 'REF', element: 2, occurrence: 2 }],
    productCode: [{ tag: 'REF', element: 2, occurrence: 3 }],
    productDescription: [{ tag: 'REF', element: 3, occurrence: 3 }],
    productInternalCode: [{ tag: 'REF', element: 4, component: 2, occurrence: 3 }],
    coverageNumber: [{ tag: 'REF', element: 2, occurrence: 4 }],
    coverageDescription: [{ tag: 'REF', element: 3, occurrence: 4 }],
    serviceCategory: [{ tag: 'REF', element: 4, component: 1, occurrence: 4 }],
    serviceClassCode: [{ tag: 'REF', element: 4, component: 2, occurrence: 4 }],
    initialMaxBenefit: [{ tag: 'REF', element: 4, component: 4, occurrence: 4 }],
    coverageTypeCode: [{ tag: 'REF', element: 2, occurrence: 5 }],
    coverageSubtypeCode: [{ tag: 'REF', element: 4, component: 2, occurrence: 5 }],
    applicationCode: [{ tag: 'REF', element: 2, occurrence: 6 }],
    specialtyCode: [{ tag: 'REF', element: 2, occurrence: 7 }],
    relationshipCode: [{ tag: 'REF', element: 2, occurrence: 8 }],
    planNumber: [{ tag: 'REF', element: 2, occurrence: 9 }],
    originalAuthNumber: [{ tag: 'REF', element: 4, component: 2, occurrence: 9 }],
    accidentType: [{ tag: 'REF', element: 2, occurrence: 10 }],
    contractorDocumentType: [{ tag: 'REF', element: 2, occurrence: 11 }],
    contractorIdQualifier: [{ tag: 'REF', element: 4, component: 1, occurrence: 11 }],
    contractorId: [{ tag: 'REF', element: 4, component: 2, occurrence: 11 }],
    accidentDate: [{ tag: 'DTP', element: 3, occurrence: 1 }],
    contractorEntityType: [{ tag: 'NM1', element: 2, occurrence: 4 }],
    contractorLastName: [{ tag: 'NM1', element: 3, occurrence: 4 }],
    contractorFirstName: [{ tag: 'NM1', element: 4, occurrence: 4 }],
    contractorSecondLastName: [{ tag: 'NM1', element: 12, occurrence: 4 }],
  };
}
