import { ConCod271DTO } from 'src/app/entities/dtos/service/conCod271.dto';

import { FieldMap, X12ManagerConfig } from '../x12.manager';

import { ConCod271DetailConfig } from './271ConCodDetail.config';

export class ConCod271Config implements X12ManagerConfig<ConCod271DTO> {
  readonly segmentDelimiter: string = '~';
  readonly elementDelimiter: string = '*';
  readonly componentDelimiter: string = ':';

  readonly segmentSequence: string[] = [
    'ISA',
    'GS',
    'ST',
    'BHT',
    'HL',
    'NM1',
    'REF',
    'DTP',
    'HL',
    'NM1',
    'HL',
    'NM1',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'REF',
    'DMG',
    'DTP',
    'DTP',
    'NM1',
    'REF',
    'NM1',
    'REF',
    'DTP',
    'SE',
    'GE',
    'IEA',
  ];

  readonly segmentLength: Record<string, number> = {
    ISA: 16,
    GS: 8,
    ST: 3,
    BHT: 2,
    HL: 4,
    NM1: 12,
    REF: 4,
    DTP: 3,
    DMG: 5,
    SE: 2,
    GE: 2,
    IEA: 2,
  };

  readonly fieldMap: FieldMap<ConCod271DTO> = {
    ipressId: [
      { tag: 'ISA', element: 6, occurrence: 1 },
      { tag: 'GS', element: 2, occurrence: 1 },
    ],
    iafaId: [
      { tag: 'ISA', element: 8, occurrence: 1 },
      { tag: 'GS', element: 3, occurrence: 1 },
    ],
    gsTransactionDate: [{ tag: 'GS', element: 4, occurrence: 1 }],
    gsTransactionTime: [{ tag: 'GS', element: 5, occurrence: 1 }],
    isaDate: [{ tag: 'ISA', element: 9, occurrence: 1 }],
    isaTime: [{ tag: 'ISA', element: 10, occurrence: 1 }],
    correlationId: [
      { tag: 'ISA', element: 13, occurrence: 1 },
      { tag: 'IEA', element: 2, occurrence: 1 },
    ],
    transactionId: [{ tag: 'ST', element: 1, occurrence: 1 }],
    purposeCode: [{ tag: 'BHT', element: 2, occurrence: 1 }],
    controlNumber: [
      { tag: 'GS', element: 6, occurrence: 1 },
      { tag: 'GE', element: 2, occurrence: 1 },
    ],
    transactionSetControlNumber: [
      { tag: 'ST', element: 2, occurrence: 1 },
      { tag: 'SE', element: 2, occurrence: 1 },
    ],
    senderCategory: [{ tag: 'NM1', element: 2, occurrence: 1 }],
    senderUser: [{ tag: 'REF', element: 2, occurrence: 1 }],
    senderPassword: [{ tag: 'REF', element: 4, component: 2, occurrence: 1 }],
    photoUploadDate: [{ tag: 'DTP', element: 3, occurrence: 1 }],
    receiverCategory: [{ tag: 'NM1', element: 2, occurrence: 2 }],
    receiverTaxId: [{ tag: 'NM1', element: 9, occurrence: 2 }],
    patientCategory: [{ tag: 'NM1', element: 2, occurrence: 3 }],
    patientLastName: [{ tag: 'NM1', element: 3, occurrence: 3 }],
    patientFirstName: [{ tag: 'NM1', element: 4, occurrence: 3 }],
    patientAffiliation: [{ tag: 'NM1', element: 9, occurrence: 3 }],
    patientSecondLastName: [{ tag: 'NM1', element: 12, occurrence: 3 }],
    patientStatusCode: [{ tag: 'REF', element: 2, occurrence: 2 }],
    patientDocumentType: [{ tag: 'REF', element: 2, occurrence: 3 }],
    patientDocumentNumber: [{ tag: 'REF', element: 4, component: 2, occurrence: 3 }],
    patientIdentifier: [{ tag: 'REF', element: 2, occurrence: 4 }],
    patientContractNumber: [{ tag: 'REF', element: 2, occurrence: 5 }],
    policyNumber: [{ tag: 'REF', element: 4, component: 2, occurrence: 5 }],
    certificateNumber: [{ tag: 'REF', element: 4, component: 4, occurrence: 5 }],
    policyTypeCode: [{ tag: 'REF', element: 4, component: 6, occurrence: 5 }],
    productCode: [{ tag: 'REF', element: 2, occurrence: 6 }],
    productDescription: [{ tag: 'REF', element: 3, occurrence: 6 }],
    planNumber: [{ tag: 'REF', element: 2, occurrence: 7 }],
    healthPlanType: [{ tag: 'REF', element: 4, component: 2, occurrence: 7 }],
    currencyCode: [{ tag: 'REF', element: 4, component: 4, occurrence: 7 }],
    relationshipCode: [{ tag: 'REF', element: 2, occurrence: 8 }],
    benefitSubjectCode: [{ tag: 'REF', element: 2, occurrence: 9 }],
    benefitSubjectNumber: [{ tag: 'REF', element: 4, component: 2, occurrence: 9 }],
    birthDate: [{ tag: 'DMG', element: 2, occurrence: 1 }],
    gender: [{ tag: 'DMG', element: 3, occurrence: 1 }],
    maritalStatus: [{ tag: 'DMG', element: 4, occurrence: 1 }],
    coverageStartDate: [{ tag: 'DTP', element: 3, occurrence: 2 }],
    coverageEndDate: [{ tag: 'DTP', element: 3, occurrence: 3 }],
    contractorCategory: [{ tag: 'NM1', element: 2, occurrence: 4 }],
    contractorLastName: [{ tag: 'NM1', element: 3, occurrence: 4 }],
    contractorFirstName: [{ tag: 'NM1', element: 4, occurrence: 4 }],
    contractorSecondLastName: [{ tag: 'NM1', element: 12, occurrence: 4 }],
    contractorDocumentType: [{ tag: 'REF', element: 2, occurrence: 10 }],
    contractorIdRef: [{ tag: 'REF', element: 4, component: 1, occurrence: 10 }],
    contractorRefCode: [{ tag: 'REF', element: 4, component: 2, occurrence: 10 }],
    holderCategory: [{ tag: 'NM1', element: 2, occurrence: 5 }],
    holderLastName: [{ tag: 'NM1', element: 3, occurrence: 5 }],
    holderFirstName: [{ tag: 'NM1', element: 4, occurrence: 5 }],
    holderAffiliation: [{ tag: 'NM1', element: 9, occurrence: 5 }],
    holderSecondLastName: [{ tag: 'NM1', element: 12, occurrence: 5 }],
    holderDocumentType: [{ tag: 'REF', element: 2, occurrence: 11 }],
    holderDocumentNumber: [{ tag: 'REF', element: 4, component: 2, occurrence: 11 }],
    holderEnrollmentDate: [{ tag: 'DTP', element: 3, occurrence: 4 }],
    details: {
      startTag: 'DTP',
      startOccurrence: 4,
      endTag: 'SE',
      endOccurrence: 1,
      config: new ConCod271DetailConfig(),
    },
  };
}
