export enum AppointmentDocumentCategories {
  PRESCRIPTION = 'INF RECETA',
  INFORM_1 = 'Informe Consulta Externa (Alergologia)',
  INFORM_2 = 'Informe Consulta Externa (Apart. Dig. Ped.)',
  INFORM_3 = 'Informe Consulta Externa (Bariatrica)',
  INFORM_4 = 'Informe Consulta Externa (Cardiología)',
  INFORM_5 = 'Informe Consulta Externa (Cirugía Cabeza y Cuello)',
  INFORM_6 = 'Informe Consulta Externa (Cirugía Cardiaca)',
  INFORM_7 = 'Informe Consulta Externa (Cirugía Cardiovascular)',
  INFORM_8 = 'Informe Consulta Externa (Cirugía General)',
  INFORM_9 = 'Informe Consulta Externa (Cirugía Pediátrica)',
  INFORM_10 = 'Informe Consulta Externa (Cirugía Plástica)',
  INFORM_11 = 'Informe Consulta Externa (Cirugía Torax)',
  INFORM_12 = 'Informe Consulta Externa (Dermatología)',
  INFORM_13 = 'Informe Consulta Externa (Endocrinologia)',
  INFORM_14 = 'Informe Consulta Externa (Epilepsia)',
  INFORM_15 = 'Informe Consulta Externa (Gastroenterología)',
  INFORM_16 = 'Informe Consulta Externa (Geriatría)',
  INFORM_17 = 'Informe Consulta Externa (Ginecología)',
  INFORM_18 = 'Informe Consulta Externa (Hematología)',
  INFORM_19 = 'Informe Consulta Externa (Mastología)',
  INFORM_20 = 'Informe Consulta Externa (Med. Fis. Rehab.)',
  INFORM_21 = 'Informe Consulta Externa (Medicina Estética)',
  INFORM_22 = 'Informe Consulta Externa (Medicina General)',
  INFORM_23 = 'Informe Consulta Externa (Medicina Hiperbárica)',
  INFORM_24 = 'Informe Consulta Externa (Medicina Interna)',
  INFORM_25 = 'Informe Consulta Externa (Medicina Nuclear)',
  INFORM_26 = 'Informe Consulta Externa (Nefrología)',
  INFORM_27 = 'Informe Consulta Externa (Neumología)',
  INFORM_28 = 'Informe Consulta Externa (Neurocirugía)',
  INFORM_29 = 'Informe Consulta Externa (Neurologia)',
  INFORM_30 = 'Informe Consulta Externa (Nutricion)',
  INFORM_31 = 'Informe Consulta Externa (Obstetricia)',
  INFORM_32 = 'Informe Consulta Externa (Odontología)',
  INFORM_33 = 'Informe Consulta Externa (Oftalmología)',
  INFORM_34 = 'Informe Consulta Externa (Oncología Pediátrica)',
  INFORM_35 = 'Informe Consulta Externa (Oncología y Radioter.)',
  INFORM_36 = 'Informe Consulta Externa (Oncología)',
  INFORM_37 = 'Informe Consulta Externa (Otorrinolaringología)',
  INFORM_38 = 'Informe Consulta Externa (Pediatría)',
  INFORM_39 = 'Informe Consulta Externa (Pre Anestesia)',
  INFORM_40 = 'Informe Consulta Externa (Psicología)',
  INFORM_41 = 'Informe Consulta Externa (Psiquiatría)',
  INFORM_42 = 'Informe Consulta Externa (Rad. Interv.)',
  INFORM_43 = 'Informe Consulta Externa (Reumatología)',
  INFORM_44 = 'Informe Consulta Externa (Terapia de Dolor)',
  INFORM_45 = 'Informe Consulta Externa (Traumatología)',
  INFORM_46 = 'Informe Consulta Externa (Urología)',
  REST_1 = 'INF DESCANSO MEDICO',
  REST_2 = 'INF DESCANSO MEDICO CEX CLIRP',
}

export enum AppointmentDocumentTitle {
  PRESCRIPTION = 'Ver recetas médicas',
  INFORM = 'Ver informe de cita',
  REST = 'Descanso médico',
}

export enum AppointmentDocumentIcon {
  PRESCRIPTION = 1,
  INFORM_REST = 2,
}

export class AppointmentDocumentCategoriesMapper {
  private static readonly appointmentDocumentTitlesMap: Record<
    AppointmentDocumentCategories,
    AppointmentDocumentTitle
  > = {
    [AppointmentDocumentCategories.PRESCRIPTION]: AppointmentDocumentTitle.PRESCRIPTION,
    [AppointmentDocumentCategories.INFORM_1]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_2]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_3]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_4]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_5]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_6]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_7]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_8]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_9]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_10]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_11]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_12]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_13]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_14]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_15]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_16]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_17]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_18]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_19]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_20]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_21]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_22]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_23]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_24]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_25]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_26]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_27]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_28]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_29]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_30]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_31]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_32]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_33]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_34]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_35]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_36]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_37]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_38]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_39]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_40]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_41]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_42]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_43]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_44]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_45]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.INFORM_46]: AppointmentDocumentTitle.INFORM,
    [AppointmentDocumentCategories.REST_1]: AppointmentDocumentTitle.REST,
    [AppointmentDocumentCategories.REST_2]: AppointmentDocumentTitle.REST,
  };

  private static readonly appointmentDocumentIconsMap: Record<AppointmentDocumentCategories, AppointmentDocumentIcon> =
    {
      [AppointmentDocumentCategories.PRESCRIPTION]: AppointmentDocumentIcon.PRESCRIPTION,
      [AppointmentDocumentCategories.INFORM_1]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_2]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_3]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_4]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_5]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_6]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_7]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_8]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_9]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_10]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_11]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_12]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_13]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_14]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_15]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_16]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_17]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_18]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_19]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_20]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_21]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_22]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_23]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_24]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_25]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_26]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_27]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_28]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_29]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_30]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_31]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_32]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_33]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_34]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_35]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_36]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_37]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_38]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_39]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_40]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_41]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_42]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_43]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_44]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_45]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.INFORM_46]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.REST_1]: AppointmentDocumentIcon.INFORM_REST,
      [AppointmentDocumentCategories.REST_2]: AppointmentDocumentIcon.INFORM_REST,
    };

  static getAppointmentDocumentTitle(category?: string): AppointmentDocumentTitle | undefined {
    return this.appointmentDocumentTitlesMap[category as AppointmentDocumentCategories];
  }

  static getAppointmentDocumentIcon(category?: string): AppointmentDocumentIcon | undefined {
    return this.appointmentDocumentIconsMap[category as AppointmentDocumentCategories];
  }
}
